### ISSUE TITLE
php8 совместимость

### ISSUE THREAD

**Issue by kriptogenic** [cekta/di#112]
В php8 депрекейтили некоторые методы рефлекшн

<br />
<b>Deprecated</b>: Method ReflectionParameter::getClass() is deprecated in
<b>D:\OpenServer\domains\bulk.loc\vendor\cekta\di\src\Provider\Autowiring.php</b> on line <b>64</b><br />

**Comment by smpl** [comment]
8 версия php пока на dev ветке только.
Стабильная ветка поддерживает php7.* 
В 8 версии довольно сильно reflection переработали #108 #109

**Comment by kriptonuz** [comment]
Я так понимаю всё логику с Providers ты заменил, где можно найти примеры для дев ветки?

**Comment by smpl** [comment]
вот пример контейнера для разработки
```
<?php

declare(strict_types=1);

namespace Cekta\DI;

use Cekta\DI\Strategy\Autowiring;
use Cekta\DI\Strategy\Definition;
use Cekta\DI\Strategy\Implementation;
use Cekta\DI\Strategy\KeyValue;
use Psr\Container\ContainerInterface;

class Container implements ContainerInterface
{
    /**
     * @var ContainerInterface
     */
    private $container;

    /**
     * @param array<string, mixed> $params
     * @param array<string, string> $implementations
     * @param array<string, mixed> $definitions
     */
    public function __construct(array $params = [], array $implementations = [], array $definitions = [])
    {
        $containers = [];
        $containers[] = new KeyValue($params);
        $containers[] = new Implementation($implementations, $this);
        $containers[] = new Definition($definitions, $this);
        $containers[] = new Autowiring(new Reflection(), $this);
        $this->container = new Strategy(...$containers);
        $this->container = new InfiniteRecursionDetector($this->container);
        $this->container = new ArrayCache($this->container);
    }

    /**
     * @param string $id
     * @return mixed
     * @noinspection PhpMissingParamTypeInspection
     */
    public function get($id)
    {
        return $this->container->get($id);
    }

    public function has($id): bool
    {
        return $this->container->has($id);
    }
}
```

**Comment by smpl** [comment]
вообще в версии 1.0.0
я хочу чтобы пользователи либы работали с ContainerBuilder которому передаются различные параметры, имплементации и прочее и он уже создает экземпляр класса (если есть скомпилиный контейнер использует его или контейнер разработки который будет примерно как я скинул выше)
ну и другая вещь это ContainerCompaler который будет уметь компилированную версию создавать.

**Comment by kriptonuz** [comment]
Этот вариант мне больше нравится чем наследование в cekta/demo

**Comment by smpl** [comment]
да я в будующем скрою все эти детали у конечного пользователя по сути будет доступно 2 класса
1. ContainerBuilder в котором можно регистрировать свои параметры, зависимости, автоматическая иньекция в конструктор, выбор контейнера для разработки (пример что скинул выше) или скомпилированного
2. ContainerCompailer будет содержать инструменты связанные с "компиляцией" сборкой контейнера эффективной в продакшене.
