### ISSUE TITLE
Readme.md и документация

### ISSUE THREAD

**Issue by smpl** [cekta/di#15]

**Comment by FaridAkhmedov** [comment]
- Для чего нужно
- Почему именно эта библиотека
- Как разворачивать
- Как использовать
- Авторы
- Лицензия
- Контакты

**Comment by smpl** [comment]
вариантов как использовать очень много, я не хочу делать большое readme я в нем сделаю лишь очень коротко и сделаю ссылку на документацию из readme.md в /docs/ru.md например

**Comment by FaridAkhmedov** [comment]
#### Оглавление:
- Для чего нужно
- Почему именно эта библиотека
- Как разворачивать
- ~~Как использовать~~
- Авторы
- ~~Лицензия~~
- ~~Контакты~~
#### Структура:
- `/docs/ru.md`
- `/docs/en.md`
- `/docs/logo.png`
