### ISSUE TITLE
Add possibility dump/compile container

### ISSUE THREAD

**Issue by kefzce** [cekta/di#24]
this can be useful to:
1. Check for any potential issues such as circular references
2. Make the container more efficient resolving parameters/removing unused services
3. Ability to declare own "compilers" to control behavior or provide external features

Using cachedContainer also fix #16 
And it's huge performance update, suggest PhpDumper or similar, also great works with OPCache

**Comment by smpl** [comment]
1. circular references: https://github.com/cekta/di/issues/25
2. what do you mean by unused services and high efficient ?
3. it's a good idea, but I don't know how to do it now, suggestion ?
